### ISSUE TITLE
NPE on every event

### ISSUE THREAD

**Issue by danmartinez78** [iGoodie/TwitchSpawn#36]
**Describe the bug**
NPE on every event

**To Reproduce**
Configured mod
Testing widgets in streamlab for follow, donation, bits, etc

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
Server version 1.12.2
forge 14.23.5.2854
twitchspawn 0.8.1
RAD modpack 1.40a
Decocraft
PTRLib
twitchintegration
chattweaks

**Additional context**
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1088)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NullPointerException
    at net.minecraft.client.audio.PositionedSoundRecord.<init>(SourceFile:34)
    at net.minecraft.client.audio.PositionedSoundRecord.<init>(SourceFile:30)
    at net.minecraft.client.multiplayer.WorldClient.playSound(WorldClient.java:580)
    at net.minecraft.client.multiplayer.WorldClient.playSound(WorldClient.java:568)
    at net.minecraft.client.network.NetHandlerPlayClient.handleSoundEffect(NetHandlerPlayClient.java:1674)
    at net.minecraft.network.play.server.SPacketSoundEffect.processPacket(SourceFile:89)
    at net.minecraft.network.play.server.SPacketSoundEffect.processPacket(SourceFile:11)
    at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 9 more

**Comment by wolfkidsounds** [comment]
Any News on this?
