### ISSUE TITLE
Mod loading error has occurred

### ISSUE THREAD

**Issue by scaryMikrowelle** [iGoodie/TwitchSpawn#38]
Hi. I got a problem. When I wanted to start minecraft with TwitchSpawn today, an error occured:

---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 1/2/21 11:25 AM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$3980/280395604.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:418) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$3662/592655690.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.4-35.1.4.jar:35.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$432/509858326.call(Unknown Source) [forge-1.16.4-35.1.4.jar:35.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.programmer.igoodie.twitchspawn.TwitchSpawn.commonSetup(TwitchSpawn.java:68) ~[?:1.9.0] {re:classloading}
-- MOD twitchspawn --
Details:
	Mod File: twitchspawn_1.16.1-1.9.0.jar
	Failure message: TwitchSpawn (twitchspawn) encountered an error during the common_setup event phase
		java.lang.RuntimeException: TwitchSpawn loading errors occurred
	Mod Version: 1.9.0
	Mod Issue URL: https://github.com/iGoodie/TwitchSpawn/issues
	Exception message: java.lang.RuntimeException: TwitchSpawn loading errors occurred
Stacktrace:
	at net.programmer.igoodie.twitchspawn.TwitchSpawn.commonSetup(TwitchSpawn.java:68) ~[?:1.9.0] {re:classloading}
	at net.programmer.igoodie.twitchspawn.TwitchSpawn$$Lambda$3135/302450949.accept(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus$$Lambda$2957/121644275.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[?:35.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModContainer$$Lambda$3128/290509937.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 688422008 bytes (656 MB) / 1706033152 bytes (1627 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 12
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m -XX:PermSize=256m
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.4.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.4.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.4.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.4.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.4_HD_U_G5.jar OptiFine TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.4-0.4.3.jar optiforge TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.4.jar fml TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.4-0.4.3.jar FakeOptiFine TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.4-0.4.3.jar optiforgewrapper TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.4
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.4-client.jar                    |Minecraft                     |minecraft                     |1.16.4              |SIDED_SETU|NOSIGNATURE
		OptiForge-MC1.16.4-0.4.3.jar                      |OptiForge                     |optiforge                     |0.4.3               |SIDED_SETU|NOSIGNATURE
		twitchspawn_1.16.1-1.9.0.jar                      |TwitchSpawn                   |twitchspawn                   |1.9.0               |ERROR     |NOSIGNATURE
		forge-1.16.4-35.1.4-universal.jar                 |Forge                         |forge                         |35.1.4              |SIDED_SETU|22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Xaeros_Minimap_20.30.1_Forge_1.16.4.jar           |Xaero's Minimap               |xaerominimap                  |20.30.1             |SIDED_SETU|NOSIGNATURE
		jei-1.16.4-7.6.1.63.jar                           |Just Enough Items             |jei                           |7.6.1.63            |SIDED_SETU|NOSIGNATURE
	Crash Report UUID: 0ec25cdd-e126-43a0-a143-4cb5557a8d3a
	OptiFine Version: OptiFine_1.16.4_HD_U_G5
	OptiFine Build: 20201106-171901
	Render Distance Chunks: 15
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.14757 Compatibility Profile Context 20.12.1 27.20.14501.28009
	OpenGlRenderer: AMD Radeon RX 5700 XT
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 12

**Comment by scaryMikrowelle** [comment]
UPDATE: I forgot to put a chat Global Cooldown.
