### ISSUE TITLE
Can't play

### ISSUE THREAD

**Issue by Gtedu** [iGoodie/TwitchSpawn#53]
Details:
	Mod File: twitchspawn_1.16.1-1.8.2.jar
	Failure message: TwitchSpawn (twitchspawn) encountered an error during the common_setup event phase
		java.lang.RuntimeException: TwitchSpawn loading errors occurred
	Mod Version: 1.8.2
	Mod Issue URL: https://github.com/iGoodie/TwitchSpawn/issues
	Exception message: java.lang.RuntimeException: TwitchSpawn loading errors occurred
Stacktrace:
	at net.programmer.igoodie.twitchspawn.TwitchSpawn.commonSetup(TwitchSpawn.java:67) ~[twitchspawn:1.8.2] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:35.1] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_291] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_291] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_291] {}

**Comment by joshuaepstein** [comment]
You have probably messed up somewhere in the config

**Comment by joshuaepstein** [comment]
If you haven't already fixed it
